spring:
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
   # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
      # 配置获取连接等待超时的时间
    maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
      #validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
#    redis:
#      host: 192.168.149.128
#      port: 6379
#      password: 123456

  jpa:
    database: mysql
      #show-sql: true

    hibernate:
   #    ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
        hibernate:
            #  format_sql: true
            #use_sql_comments: true
          dialect: org.hibernate.dialect.MySQL5Dialect

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    suffix: .html
    prefix: classpath:/templates/
  cache:
#      ehcache:
#        config: classpath:/config/ehcache.xml
    type: redis

  http:
    multipart:
      max-file-size: 1000mb
      max-request-size: 1000mb
  messages:
    basename: i18n/messages
server:
  tomcat:
    uri-encoding: UTF-8



# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5
# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: code
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期单位ms（默认半分钟）
    syncPeriod: 30000
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10


project:
  name: 管理信息系统
  version: 1.1.0
mybatis:
  type-aliases-package: com.neo.pojo
  mapperLocations: classpath*:mapper/*Mapper.xml
logging:
  level:
    com.neo: debug

entity:
  packages: [com.neo.entity,com.neo.pojo]
pagehelper:
  reasonable: true

feifei:
  profile: D:/profile
  maxSize: 1GB
management:
  security:
    enabled: false











